In [1]:
import numpy as np

In [3]:
arr = np.arange(10).astype(float)
arr[3] = np.nan
arr[5] = 1

arr

array([ 0.,  1.,  2., nan,  4.,  1.,  6.,  7.,  8.,  9.])

In [5]:
np.unique(arr, return_counts=True, return_inverse=True)

(array([ 0.,  1.,  2.,  4.,  6.,  7.,  8.,  9., nan]),
 array([0, 1, 2, 8, 3, 1, 4, 5, 6, 7]),
 array([1, 2, 1, 1, 1, 1, 1, 1, 1]))