In [2]:
import torch
from torch import nn

#from data import *
#from net import *
#from util import *

In [9]:
torch.distributions.StudentT(3, 0.4, 2).mode

tensor(0.4000)

In [ ]:
t

In [6]:
a = torch.ones(4, 5) * 3
b = torch.ones(4, 5) * 2
a * b

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])

In [7]:
a.numpy()

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]], dtype=float32)

In [1]:
(1
+2)

3

In [2]:
net = FactorModel(FactorModel.Config())

In [3]:
net

FactorModel(
  (market_gru): GRU(64, 128, batch_first=True)
  (stock_gru): GRU(256, 128, batch_first=True)
  (stock_prior_net): MLP(
    (layers): ModuleList(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (3): Linear(in_features=128, out_features=128, bias=True)
      (4): ReLU()
      (5): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (6): Identity()
    )
  )
  (stock_post_net): MLP(
    (layers): ModuleList(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (3): Linear(in_features=128, out_features=128, bias=True)
      (4): ReLU()
      (5): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (6): Identity()
    )
  )
  (market_prior_net): MLP(
    (layers): ModuleList(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
   

In [3]:
getattr(torch.distributions, "Categorical") is torch.distributions.Categorical

True

In [5]:
torch.distributions.Categorical(torch.tensor([0.1, 0.2, 0.3, 0.4])).probs

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [3]:
out = net.predict(torch.randn(2, 12, 32, 94), torch.randn(2, 12, 32, 1))

In [4]:
out['loss']

tensor(12.1324, grad_fn=<AddBackward0>)

In [5]:
out = net.predict(torch.randn(2, 12, 32, 94), torch.randn(2, 12, 32, 1))

In [9]:
extract_scalars(out)

{'pred_loss': tensor(6.5891, grad_fn=<MseLossBackward0>),
 'kl_loss': tensor(5.8791, grad_fn=<DivBackward0>),
 'loss': tensor(12.4682, grad_fn=<AddBackward0>)}

In [13]:
out['pred_loss'].ndim

0

In [5]:
f.shape, b.shape

(torch.Size([2, 6]), torch.Size([2, 32, 6]))

In [8]:
dloader = StockSeqDataLoader(StockSeqDataLoader.Config('../data_mynp.npz', rank_return_same_time=True))

Loading data...


In [25]:
list(set(dt.year for dt in dloader.dates[dloader.valid_steps]))

[1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015]

In [27]:
dloader.get_split(('2001-01-01', '2020-12-31'))

<generator object StockSeqDataLoader.get_split at 0x7f43dc1c0190>

In [9]:
chrs, rets = dloader[0]

In [12]:
chrs.shape, rets.shape

((12, 512, 94), (12, 512))

In [14]:
loss, losses, outs = net.loss(torch.from_numpy(chrs[None]), torch.from_numpy(rets[None, ..., None]))